db:
  connection:
    connectionString: connection string for spring-boot-config-demo microservice with qa profile from local-config-repo
    userName: local-config-repo-default
    password: local-config-repo-default
  host: 127.0.0.1
  port: 2326